export enum ELogAction {
	THEM_DOT_CAP_NHAT_HOC_BA = 'THEM_DOT_CAP_NHAT_HOC_BA',
	// SUA_DOT_CAP_NHAT_HOC_BA = 'SUA_DOT_CAP_NHAT_HOC_BA',
	// XOA_DOT_CAP_NHAT_HOC_BA = 'XOA_DOT_CAP_NHAT_HOC_BA',
	// KHOI_TAO_DANH_SACH_HOC_BA = 'KHOI_TAO_DANH_SACH_HOC_BA',
	// DONG_BO_THONG_TIN_HOC_BA_SINH_VIEN = 'DONG_BO_THONG_TIN_HOC_BA_SINH_VIEN',

	// CO_VAN_CHO_Y_KIEN_HOC_BA = 'CO_VAN_CHO_Y_KIEN_HOC_BA',
	// CHUYEN_VIEN_DUYET_HOC_BA = 'CHUYEN_VIEN_DUYET_HOC_BA',
}

export const logAction: Record<ELogAction, string> = {
	[ELogAction.THEM_DOT_CAP_NHAT_HOC_BA]: 'Khởi tạo đợt học bạ',
	// [ELogAction.SUA_DOT_CAP_NHAT_HOC_BA]: '',
	// [ELogAction.XOA_DOT_CAP_NHAT_HOC_BA]: '',
	// [ELogAction.KHOI_TAO_DANH_SACH_HOC_BA]: '',
	// [ELogAction.DONG_BO_THONG_TIN_HOC_BA_SINH_VIEN]: '',
	// [ELogAction.CO_VAN_CHO_Y_KIEN_HOC_BA]: '',
	// [ELogAction.CHUYEN_VIEN_DUYET_HOC_BA]: '',
};
